ittp-user-mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE=userApp
  ports:
    - "3309:3306"
  command: mysqld --character-set-server=tis620 --collation-server=tis620_thai_ci --max-allowed-packet=1073741824
  container_name: ittp-user-mysql

ittp-user-phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=1234
    - MYSQL_ROOT_PASSWORD=1234
  links:
    - ittp-user-mysql:db
  ports:
    - "8082:80"
  container_name: ittp-user-phpmyadmin